### ISSUE TITLE
Add Latest Results

### ISSUE THREAD

**Issue by aleemb** [treffynnon/Benchmark-PHP-HHVM-Zephir#11]
Would be nice if the Readme had a graph of the latest benchmarks following any revisions to the benchmarking code.

Are these benchmark [results](https://www.simonholywell.com/static/files/2014-02-28/index.html) current (as I noticed that this project now has `script.sh` to pre-warm the cache for the HHVM issue)? If not, where can I find the latest results?

**Comment by treffynnon** [comment]
I don't deem it difficult to set this project up and run it. You'll want results on your own hardware anyway.
