### ISSUE TITLE
Add PHPQB to the test suite?

### ISSUE THREAD

**Issue by damienalexandre** [treffynnon/Benchmark-PHP-HHVM-Zephir#4]
Hi,
first a warm thank you for this benchmark, I've learn some stuffs on Zephir and HHVM thanks of it.

There is another alternative trending way of running PHP stuff I'm aware of, but I've never got the chance to compare it with raw PHP and HHVM: http://www.php-qb.net/ - specially done for computing intensive tasks like this benchmark (lets ping @chung-leong ! :wave:).

Cheers,
Damien

**Comment by treffynnon** [comment]
That was definitely something I had thought about adding since he announced
it on the PECL mailing list. Just haven't quite got to it yet. I have been
working on the FCGI branch at the moment.

**Comment by damienalexandre** [comment]
Great to hear :neckbeard: 

Oh there is also http://www.php-compiler.net/ - but... Microsoft® only :no_good:.

**Comment by treffynnon** [comment]
Phalanger would be difficult to implement as this is all bash/unix based. It would be similar to http://quercus.caucho.com too.

**Comment by treffynnon** [comment]
Some work has started in a new branch: https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir/tree/php-qb/cli-php-qb

Completely untested as yet.

**Comment by treffynnon** [comment]
OK, so this has now been integrated for FastCGI tests (currently delayed by HHVM with issue #7) over at https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir/tree/fcgi/fcgi-php-qb and CLI over on master at https://github.com/treffynnon/Benchmark-PHP-HHVM-Zephir/tree/master/cli-php-qb

**Comment by damienalexandre** [comment]
Awesome :heart_eyes:
