### ISSUE TITLE
[JPHP] Add test

### ISSUE THREAD

**Issue by treffynnon** [treffynnon/Benchmark-PHP-HHVM-Zephir#9]
https://github.com/dim-s/jphp

**Comment by treffynnon** [comment]
``` bash
sudo add-apt-repository ppa:cwchien/gradle
sudo apt-get update
sudo apt-get install gradle
```

**Comment by treffynnon** [comment]
Looking for a pull request on this one as I don't have any more time for writing this benchmarking suite. @dim-s any interest?

**Comment by dim-s** [comment]
Hi, I have no time for this, but I can give some tips for testing JPHP:
- Execution in the global and local scopes:

```
// global scope
for($i = 0; $i < 100500; $i++){
    /// ...
}

// local scope - ~2x faster than in the global scope
funtion test(){
    for($i = 0; $i < 100500; $i++){
       // ...
    }
}
test();
```
- In JPHP some functions are not yet implemented
- JPHP has a smart optimizer that can give false results, for example:

```
for ($i = 0; $i < 100500; $i++){
    // it will be calculated only one time at compile-time
    $x = cos(1) + 3 / 4 . ("foobar" . __FILE__); 
}
```

**Comment by treffynnon** [comment]
Closing as won't fix
